# -----------------------------------------------------
# General window layout and colors
# name: "Default"
# -----------------------------------------------------

general {
    gaps_in = 2
    gaps_out = 1
    border_size = 2
    # col.active_border = $color11
    # col.inactive_border = $color8
    layout = dwindle
    resize_on_border = true
}

dwindle {
    pseudotile = true
    preserve_split = true
}

gestures {
  workspace_swipe = true
  workspace_swipe_fingers = 4
  workspace_swipe_distance = 500
  workspace_swipe_invert = true
  workspace_swipe_min_speed_to_force = 30
  workspace_swipe_cancel_ratio = 0.5
  workspace_swipe_create_new = true
  workspace_swipe_forever = true
}

binds {
  # workspace_back_and_forth = true
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}

windowrule = opacity 0.99 0.95, class:.*
