# -----------------------------------------------------
# General window decoration
# name: "Default"
# -----------------------------------------------------

decoration {
    # rounding = 10
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0
    dim_inactive = false

    # blur {
    #     enabled = true
    #     size = 6
    #     passes = 2
    #     new_optimizations = on
    #     ignore_opacity = true
    #     xray = true
    #     # blurls = waybar
    # }
    #
    # shadow {
    #     enabled = true
    #     range = 30
    #     render_power = 3
    #     color = 0x66000000
    # }
}

group {
    # col.border_active = $on_surface
    # col.border_inactive = $on_primary_fixed
    groupbar {
        enabled = true
        # render_titles = false
        # col.active = $on_primary
        # col.inactive = $on_tertiary
    }
}

