# Extra autostart processes
# exec-once = uwsm app -- my-service
exec-once = wl-paste --type text --watch cliphist store # Stores only text data

exec-once = wl-paste --type image --watch cliphist store # Stores only image data

# Monitor change daemon - handles HDMI disconnect while lid closed
exec-once = ~/.config/hypr/z-scripts/monitor-daemon.sh
