-enable-features=UseOzonePlatform -ozone-platform=wayland --high-dpi-support=1 --gtk-version=4
--load-extension=/usr/share/omarchy/default/chromium/extensions/yt-dlp,/usr/share/omarchy/default/chromium/extensions/whatsapp-slim
--password-store=gnome-libsecret
