unbind r
bind r source-file ~/.tmux.conf

set -g prefix M-z

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -L

set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm-kitty:RGB"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# List of plugins

set -g @plugin 'catppuccin/tmux#v2.1.2'
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @vim_navigator_mapping_left "C-h"  # use C-h only
set -g @vim_navigator_mapping_right "C-l"  # use C-l only
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_number_position 'right'
set -g @catppuccin_window_status 'no'
set -g @catppuccin_window_text '#W'
set -g @catppuccin_window_current_fill 'number'
set -g @catppuccin_window_current_text '#W'
set -g @catppuccin_window_current_color '#{E:@thm_surface_2}'

set -g @vim_navigator_prefix_mapping_clear_screen ""
# load custom moudules
# source -F '#{d:current_file}/custom_modules/ctp_cpu.conf'
# source -F '#{d:current_file}/custom_modules/ctp_memory.conf'
# source -F '#{d:current_file}/custom_modules/primary_ip.conf'

# set default directory for new windows in this session to current directory:
bind M-c attach-session -c "#{pane_current_path}"

# set left and right status bar
set -g allow-rename off
set -g status-position top
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100
set -g status-left '#{E:@catppuccin_status_session} '
set -gF status-right '#{E:@catppuccin_status_primary_ip}'
set -agF status-right '#{E:@catppuccin_status_ctp_cpu}'
set -agF status-right '#{E:@catppuccin_status_ctp_memory}'
if 'test -r /sys/class/power_supply/BAT*' {
  set -agF status-right '#{E:@catppuccin_status_battery}'
}
set -ag status-right '#{E:@catppuccin_status_date_time}'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'


##### Display Popups ##### 

bind l display-popup \
  -d "#{pane_current_path}" \
  -w 85% \
  -h 85% \
  -E "lazygit"
bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
bind Tab display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
