# ----------------------------------------------------- 
# Monitor Setup
# name: "Default"
# ----------------------------------------------------- 

#monitor=,preferred,auto,1

monitor=eDP-1,preferred,0x0,1.9
monitor=,preferred,auto-up,auto
