# ----------------------------------------------------- 
# Monitor Setup
# name: "Default"
# ----------------------------------------------------- 

#monitor=,preferred,auto,1

monitor=eDP-1,preferred,0x0,1.33
#monitor=DP-1,preferred,auto-right,1
monitor=desc:LG Electronics LG HDR WFHD 0x00040133,preferred,auto-right,auto
#monitor=desc:LG Electronics LG IPS FULLHD 0x01010101,preferred,4244x0,auto, transform, 3
monitor=desc:LG Electronics LG IPS FULLHD 0x01010101,preferred,auto-right,auto, transform, 3
monitor=desc:Samsung Electric Company S22A33x H9DX601793,preferred,auto-left,auto
monitor=,preferred,auto-left,1

